## Credit Card Fraud Detection Using Logistic Regression

In [1]:
## Data Analysis Phase
## MAin aim is to understand more about the data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
## Display all the columns of the dataframe

pd.pandas.set_option('display.max_columns',None)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [9]:
##loading the dataset
cc_dataset = pd.read_csv("creditcard.csv")

In [12]:
## Reading the first 5 rows of the dataset
cc_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [14]:
## Reading the last 5 rows of the dataset
cc_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,-1.593105,2.711941,-0.689256,4.626942,-0.924459,1.107641,1.991691,0.510632,-0.682920,1.475829,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,-0.150189,0.915802,1.214756,-0.675143,1.164931,-0.711757,-0.025693,-1.221179,-1.545556,0.059616,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,0.411614,0.063119,-0.183699,-0.510602,1.329284,0.140716,0.313502,0.395652,-0.577252,0.001396,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,-1.933849,-0.962886,-1.042082,0.449624,1.962563,-0.608577,0.509928,1.113981,2.897849,0.127434,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,-1.040458,-0.031513,-0.188093,-0.084316,0.041333,-0.302620,-0.660377,0.167430,-0.256117,0.382948,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [15]:
## Checking the rows and columns of the dataset
cc_dataset.shape

(284807, 31)

In [18]:
## Dataset Information
cc_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
Time      284807 non-null float64
V1        284807 non-null float64
V2        284807 non-null float64
V3        284807 non-null float64
V4        284807 non-null float64
V5        284807 non-null float64
V6        284807 non-null float64
V7        284807 non-null float64
V8        284807 non-null float64
V9        284807 non-null float64
V10       284807 non-null float64
V11       284807 non-null float64
V12       284807 non-null float64
V13       284807 non-null float64
V14       284807 non-null float64
V15       284807 non-null float64
V16       284807 non-null float64
V17       284807 non-null float64
V18       284807 non-null float64
V19       284807 non-null float64
V20       284807 non-null float64
V21       284807 non-null float64
V22       284807 non-null float64
V23       284807 non-null float64
V24       284807 non-null float64
V25       284807 non-null float64
V26       284807 non-null float64
V27       284807 non-null float64
V28       284807 non-null float64
Amount    284807 non-null float64
Class     284807 non-null int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [19]:
## Checking the missing values in the dataset

cc_dataset.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

There are no missing values in the dataset

In [20]:
## Check the distribution of legit transactions and fraud transactions
## 0- Legit Transactions
## 1 - Fraud Transactions

cc_dataset.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

We can see that the dataset is completely unbalanced

In [24]:
## Separating the data for analysis

legit = cc_dataset[cc_dataset["Class"]==0]
fraud = cc_dataset[cc_dataset["Class"]==1]

In [25]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

##### Statistical Measures of the data

In [27]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [28]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [29]:
## Compare the values for both transactions

cc_dataset.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,0.009824,-0.006576,0.010832,0.000189,0.012064,0.000161,0.007164,0.011535,0.003887,-0.001178,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,-5.676883,3.800173,-6.259393,-0.109334,-6.971723,-0.092929,-4.139946,-6.665836,-2.246308,0.680659,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

##### Dealing with unbalanced data

UnderSampling

Build a sample dataset containing similar distribution of legit transactions and the fraud transactions

No. of Fraud Transactions = 492

So we would take random 492 transactions from the legit dataset and then join it with fraud transactions so that there would be uniformity in the class feature and the distribution would be even

In [30]:
legit_sample = legit.sample(n=492)

In [36]:
## Concatenating two dataframes
new_cc_dataset = pd.concat([legit_sample,fraud], axis=0)

In [37]:
## Checking the first 5 rows of the new df

new_cc_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
159656,112771.0,1.929586,-0.415172,-0.106038,0.560340,-0.779746,-0.290080,-0.697248,0.054466,0.888533,0.184645,0.878124,1.382791,0.600689,-0.159161,-0.438155,0.447495,-0.752035,0.430506,-0.075310,-0.157412,0.233158,0.890414,0.148543,0.141204,-0.265975,0.360105,-0.005307,-0.051817,9.95,0
220971,142378.0,1.988059,-0.460356,-0.416769,0.261133,-0.565768,-0.137178,-0.714209,0.076166,0.928296,0.213566,0.434325,0.899486,0.229388,-0.025943,-0.138808,0.671771,-0.943102,0.707559,0.075052,-0.167994,0.272759,0.972038,0.058753,-0.336212,-0.190903,0.646799,-0.027224,-0.063261,5.99,0
167260,118579.0,-1.425615,-0.476318,-4.378084,-0.188049,-10.379747,6.685729,12.169882,-4.033903,-0.928643,-1.846245,0.872569,0.003979,0.570129,-0.075561,-0.975894,1.079812,-1.226794,0.038398,-0.004447,-1.587508,0.824884,-0.171771,0.733107,-0.164284,-0.455545,0.125111,1.609144,-0.991008,2541.80,0
243678,152026.0,-0.250419,-0.532396,0.704296,-0.616342,1.020837,-1.362238,0.258950,-0.305411,0.871346,-0.567087,-0.919283,0.996514,1.330808,-0.555253,-0.496357,0.222401,-1.144194,-0.247601,-0.939906,0.097988,0.115068,0.406878,0.627245,0.022611,-2.191786,-1.107908,0.207505,0.175449,31.78,0
153504,99249.0,-0.924370,0.747546,1.729800,0.724626,1.434750,2.717563,0.287399,0.550167,1.431347,-0.491202,1.271324,-2.184082,0.529915,1.244808,-1.254825,-1.435814,1.336236,-0.837548,0.635453,0.051332,-0.688845,-1.235825,-0.060493,-1.101239,0.196379,-0.774659,0.085752,-0.121034,20.70,0

In [38]:
## Checking the last 5 rows of the new df

new_cc_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,-5.587794,2.115795,-5.417424,-1.235123,-6.665177,0.401701,-2.897825,-4.570529,-1.315147,0.391167,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,-3.232153,2.858466,-3.096915,-0.792532,-5.210141,-0.613803,-2.155297,-3.267116,-0.688505,0.737657,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,-3.463891,1.794969,-2.775022,-0.418950,-4.057162,-0.712616,-1.603015,-5.035326,-0.507000,0.266272,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,-5.245984,1.933520,-5.030465,-1.127455,-6.416628,0.141237,-2.549498,-4.614717,-1.478138,-0.035480,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,-0.888722,0.491140,0.728903,0.380428,-1.948883,-0.832498,0.519436,0.903562,1.197315,0.593509,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [39]:
new_cc_dataset.Class.value_counts()

1    492
0    492
Name: Class, dtype: int64

Now the dataset is balanced

In [40]:
## Compare the values for both transactions

new_cc_dataset.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,98607.855691,-0.013877,-0.000751,-0.044590,-0.008220,0.137150,0.074212,-0.033473,0.057875,-0.018822,0.000419,-0.069475,-0.016341,-0.044453,0.034003,0.062339,0.075268,0.014491,-0.086637,-0.035464,-0.010600,-0.002973,0.022609,-0.017136,0.006062,-0.038776,0.014172,0.006089,0.008475,83.917866
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,-5.676883,3.800173,-6.259393,-0.109334,-6.971723,-0.092929,-4.139946,-6.665836,-2.246308,0.680659,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

When compared with the earlier comparison we can see that the data is not changed much and is almost similar. This tells us that the nature of the dataset is not changed. This step is to check if we have got a good sample or bad sample

In [41]:
## Splitting the dataset into features and targets

X=new_cc_dataset.drop("Class", axis=1)
y=new_cc_dataset["Class"]

In [42]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
159656,112771.0,1.929586,-0.415172,-0.106038,0.560340,-0.779746,-0.290080,-0.697248,0.054466,0.888533,0.184645,0.878124,1.382791,0.600689,-0.159161,-0.438155,0.447495,-0.752035,0.430506,-0.075310,-0.157412,0.233158,0.890414,0.148543,0.141204,-0.265975,0.360105,-0.005307,-0.051817,9.95
220971,142378.0,1.988059,-0.460356,-0.416769,0.261133,-0.565768,-0.137178,-0.714209,0.076166,0.928296,0.213566,0.434325,0.899486,0.229388,-0.025943,-0.138808,0.671771,-0.943102,0.707559,0.075052,-0.167994,0.272759,0.972038,0.058753,-0.336212,-0.190903,0.646799,-0.027224,-0.063261,5.99
167260,118579.0,-1.425615,-0.476318,-4.378084,-0.188049,-10.379747,6.685729,12.169882,-4.033903,-0.928643,-1.846245,0.872569,0.003979,0.570129,-0.075561,-0.975894,1.079812,-1.226794,0.038398,-0.004447,-1.587508,0.824884,-0.171771,0.733107,-0.164284,-0.455545,0.125111,1.609144,-0.991008,2541.80
243678,152026.0,-0.250419,-0.532396,0.704296,-0.616342,1.020837,-1.362238,0.258950,-0.305411,0.871346,-0.567087,-0.919283,0.996514,1.330808,-0.555253,-0.496357,0.222401,-1.144194,-0.247601,-0.939906,0.097988,0.115068,0.406878,0.627245,0.022611,-2.191786,-1.107908,0.207505,0.175449,31.78
153504,99249.0,-0.924370,0.747546,1.729800,0.724626,1.434750,2.717563,0.287399,0.550167,1.431347,-0.491202,1.271324,-2.184082,0.529915,1.244808,-1.254825,-1.435814,1.336236,-0.837548,0.635453,0.051332,-0.688845,-1.235825,-0.060493,-1.101239,0.196379,-0.774659,0.085752,-0.121034,20.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,-5.587794,2.115795,-5.417424,-1.235123,-6.665177,0.401701,-2.897825,-4.570529,-1.315147,0.391167,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,-3.232153,2.858466,-3.096915,-0.792532,-5.210141,-0.613803,-2.155297,-3.267116,-0.688505,0.737657,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,-3.463891,1.794969,-2.775022,-0.418950,-4.057162,-0.712616,-1.603015,-5.035326,-0.507000,0.266272,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,-5.245984,1.933520,-5.030465,-1.127455,-6.416628,0.141237,-2.549498,-4.614717,-1.478138,-0.035480,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,-0.888722,0.491140,0.728903,0.380428,-1.948883,-0.832498,0.519436,0.903562,1.197315,0.593509,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [43]:
y

159656    0
220971    0
167260    0
243678    0
153504    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [45]:
## Performing a train test split

X_train,X_test, y_train,y_test  = train_test_split(X,y,test_size = 0.2, stratify = y, random_state =2)

In [46]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

In [48]:
## Model Training

model = LogisticRegression()

In [49]:
## Training the Logistic Regression Model with Training data
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [58]:
#Predicting data with the test dataset
y_pred_test = model.predict(X_test)

In [59]:
#Comparing the actual and predicted values
pd.DataFrame({"Actual Value": y_test, "Predicted Value": y_pred_test}).head()

        Actual Value  Predicted Value
247995             1                1
23680              0                0
250429             0                0
187319             0                0
15451              1                1

In [60]:
## Model Evaluation

testing_data_accuracy = accuracy_score(y_test,y_pred)
testing_data_accuracy

0.9137055837563451

In [61]:
#Predicting data with the train dataset
y_pred_train = model.predict(X_train)

In [62]:
training_data_accuracy = accuracy_score(y_train,y_pred_train)
training_data_accuracy

0.9250317662007624